# docker-compose.yml
version: "3"
services:
  postgres:
    image: postgres:10.4
    ports:
      - "5432:5432"
    env_file:
      - .env

  app:
    build: .
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      PORT: 3000
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: npm start
    volumes:
      - .:/app/
      - /app/node_modules
